export default {
    python: "Python",
    js: "JavaScript",
    sql: "SQL",
    sqlite: "SQLite",
    postgreSql: "PostgreSQL",
    html: "HTML",
    css: "CSS",
    sass: "SASS",
    git: "Git & GitHub",
    linux: "Linux",
    networking: "Networking",
    vscode: "VSCode",
    docker: "Docker",
    wireshark: "Wireshark",
    fastapi: "FastAPI",
    django: "Django",
    pyqt5: "PyQt5",
    flask: "Flask",
    ml: "Machine Learning",
    nlp: "NLP",
    webpack: "WebPack",
    cybersecurity: "Cyber Security",
}
